tag merge handling in TagEdit component
Still don't work because the merge route fail to do the job without error

error: [Tags] Error merging tag 9862324a-157b-47d9-8a4d-c2f17baee4ee and 064b332b-7925-4ddc-b32d-b29e45f37dac : error: une valeur NULL viole la contrainte NOT NULL de la colonne « tagfile »